name: frustration_detector
version: 0.1.0
description: Library for detecting user frustration
homepage: https://github.com/dustinlessard-wf/frustration-detector-dart

environment:
  sdk: ">=2.11.0 <3.0.0"

dev_dependencies:
  test: ^1.15.1
  