name: frustration_detector
version: 0.1.0
description: Library for detecting user frustration
homepage: https://github.com/dustinlessard-wf/frustration-detector-dart

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  rxdart: 0.27.0

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  test: ^1.15.1
  